version: "3.8"


services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html


volumes:
  mysql-data